### PR TITLE
Feature/webpage setup1

### PR DESCRIPTION
**Pull request by fersanz-87**
I have added some changes on the ready set team photos, corrections on the text and moved position on some pics. I just miss adding some changes on the 8 point check list picture, which is going to be shared from one of my coworkers.

### CODE REVIEW

**Comment by Ealanisln** [comment]
Hey @fersanz-87, Rochelle Lean Tan photo still having errors. Please check network tab error and try to fix it. Thanks. 

https://ready-9jtgzcn20-ready-sets-projects.vercel.app/about

Screenshot 2024-10-08 at 2 06 58 p m
Screenshot 2024-10-08 at 2 06 41 p m

**Comment by fersanz-87** [comment]
I added Rochelle Lean pic. Issue was on the pic name, it was:
image: "/images/team/Tan_Rochelle.png" instead of image: "/images/team/Tan_Rochelle_Lean.png", which is the correct pic.

**Comment by fersanz-87** [comment]
Please hold on, I was running the code locally and the issue persist. Let me fix it.

**Comment by fersanz-87** [comment]
Rochelle Lean pic added. Issue was with a dot (.)

**Pull request merged**
